// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: stockpb/stock.proto

package stockpb

import (
	orderpb "github.com/Hypocrite/gorder/common/genproto/orderpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []string               `protobuf:"bytes,1,rep,name=ItemIDs,proto3" json:"ItemIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsReq) Reset() {
	*x = GetItemsReq{}
	mi := &file_stockpb_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsReq) ProtoMessage() {}

func (x *GetItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsReq.ProtoReflect.Descriptor instead.
func (*GetItemsReq) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsReq) GetItemIDs() []string {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

type GetItemsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.Item        `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRes) Reset() {
	*x = GetItemsRes{}
	mi := &file_stockpb_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRes) ProtoMessage() {}

func (x *GetItemsRes) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRes.ProtoReflect.Descriptor instead.
func (*GetItemsRes) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemsRes) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckIfItemInStockReq struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfItemInStockReq) Reset() {
	*x = CheckIfItemInStockReq{}
	mi := &file_stockpb_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemInStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemInStockReq) ProtoMessage() {}

func (x *CheckIfItemInStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemInStockReq.ProtoReflect.Descriptor instead.
func (*CheckIfItemInStockReq) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{2}
}

func (x *CheckIfItemInStockReq) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckIfItemInStockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InStock       int32                  `protobuf:"varint,1,opt,name=InStock,proto3" json:"InStock,omitempty"`
	Items         []*orderpb.Item        `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfItemInStockRes) Reset() {
	*x = CheckIfItemInStockRes{}
	mi := &file_stockpb_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemInStockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemInStockRes) ProtoMessage() {}

func (x *CheckIfItemInStockRes) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemInStockRes.ProtoReflect.Descriptor instead.
func (*CheckIfItemInStockRes) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *CheckIfItemInStockRes) GetInStock() int32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *CheckIfItemInStockRes) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_stockpb_stock_proto protoreflect.FileDescriptor

const file_stockpb_stock_proto_rawDesc = "" +
	"\n" +
	"\x13stockpb/stock.proto\x12\astockpb\x1a\x13orderpb/order.proto\"'\n" +
	"\vGetItemsReq\x12\x18\n" +
	"\aItemIDs\x18\x01 \x03(\tR\aItemIDs\"2\n" +
	"\vGetItemsRes\x12#\n" +
	"\x05Items\x18\x01 \x03(\v2\r.orderpb.ItemR\x05Items\"H\n" +
	"\x15CheckIfItemInStockReq\x12/\n" +
	"\x05Items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05Items\"V\n" +
	"\x15CheckIfItemInStockRes\x12\x18\n" +
	"\aInStock\x18\x01 \x01(\x05R\aInStock\x12#\n" +
	"\x05Items\x18\x02 \x03(\v2\r.orderpb.ItemR\x05Items2\x9c\x01\n" +
	"\fStockService\x126\n" +
	"\bGetItems\x12\x14.stockpb.GetItemsReq\x1a\x14.stockpb.GetItemsRes\x12T\n" +
	"\x12CheckIfItemInStock\x12\x1e.stockpb.CheckIfItemInStockReq\x1a\x1e.stockpb.CheckIfItemInStockResB5Z3github.com/Hypocrite/gorder/common/genproto/stockpbb\x06proto3"

var (
	file_stockpb_stock_proto_rawDescOnce sync.Once
	file_stockpb_stock_proto_rawDescData []byte
)

func file_stockpb_stock_proto_rawDescGZIP() []byte {
	file_stockpb_stock_proto_rawDescOnce.Do(func() {
		file_stockpb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)))
	})
	return file_stockpb_stock_proto_rawDescData
}

var file_stockpb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stockpb_stock_proto_goTypes = []any{
	(*GetItemsReq)(nil),              // 0: stockpb.GetItemsReq
	(*GetItemsRes)(nil),              // 1: stockpb.GetItemsRes
	(*CheckIfItemInStockReq)(nil),    // 2: stockpb.CheckIfItemInStockReq
	(*CheckIfItemInStockRes)(nil),    // 3: stockpb.CheckIfItemInStockRes
	(*orderpb.Item)(nil),             // 4: orderpb.Item
	(*orderpb.ItemWithQuantity)(nil), // 5: orderpb.ItemWithQuantity
}
var file_stockpb_stock_proto_depIdxs = []int32{
	4, // 0: stockpb.GetItemsRes.Items:type_name -> orderpb.Item
	5, // 1: stockpb.CheckIfItemInStockReq.Items:type_name -> orderpb.ItemWithQuantity
	4, // 2: stockpb.CheckIfItemInStockRes.Items:type_name -> orderpb.Item
	0, // 3: stockpb.StockService.GetItems:input_type -> stockpb.GetItemsReq
	2, // 4: stockpb.StockService.CheckIfItemInStock:input_type -> stockpb.CheckIfItemInStockReq
	1, // 5: stockpb.StockService.GetItems:output_type -> stockpb.GetItemsRes
	3, // 6: stockpb.StockService.CheckIfItemInStock:output_type -> stockpb.CheckIfItemInStockRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stockpb_stock_proto_init() }
func file_stockpb_stock_proto_init() {
	if File_stockpb_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stockpb_stock_proto_goTypes,
		DependencyIndexes: file_stockpb_stock_proto_depIdxs,
		MessageInfos:      file_stockpb_stock_proto_msgTypes,
	}.Build()
	File_stockpb_stock_proto = out.File
	file_stockpb_stock_proto_goTypes = nil
	file_stockpb_stock_proto_depIdxs = nil
}
